source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TraceJobs_Example', :exclusive => true do
  pod "TraceJobs", :path => "../"
end

target 'TraceJobs_Tests', :exclusive => true do
  pod "TraceJobs", :path => "../"

  
end
